-- Create a table for sessions
create table public.sessions (
  session_id uuid not null primary key,
  user_id text, -- Can be optional if anonymous
  start_time timestamp with time zone default timezone('utc'::text, now()) not null,
  end_time timestamp with time zone,
  summary text,
  duration_seconds integer
);

-- Create a table for events (logs)
create table public.events (
  event_id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(session_id) on delete cascade not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  event_type text not null, -- 'user_message', 'ai_message', 'tool_call', 'tool_result'
  content text
);

-- Enable Row Level Security (RLS) if needed, for now we can leave it open or simple
alter table public.sessions enable row level security;
alter table public.events enable row level security;

-- Create simple policies (optional, depends on if we have auth)
-- For this assignment, we might skip auth or allow public insert for the backend key
create policy "Allow public insert" on public.sessions for insert with check (true);
create policy "Allow public select" on public.sessions for select using (true);
create policy "Allow public update" on public.sessions for update using (true);

create policy "Allow public insert" on public.events for insert with check (true);
create policy "Allow public select" on public.events for select using (true);
